update theme and 2024 summary
fix the github action

diff --git a/.github/workflows/pb.yml b/.github/workflows/pb.yml
--- a/.github/workflows/pb.yml
+++ b/.github/workflows/pb.yml
@@ -8,34 +8,44 @@ jobs:
     name: A job to deploy blog.
     steps:
     - name: Checkout
-      uses: actions/checkout@v1
+      uses: actions/checkout@v3
       with:
-        submodules: true # Checkout private submodules(themes or something else).
-    
-    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
+        submodules: true 
+
+    - name: Setup Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '20'
+
     - name: Cache node modules
-      uses: actions/cache@v1
+      uses: actions/cache@v3
       id: cache
       with:
         path: node_modules
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-node-
+
     - name: Install Dependencies
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: npm ci
-    
-    # Deploy hexo blog website.
+      run: |
+        npm install hexo-util --save
+        npm ci
+
+    - name: Fix vulnerabilities
+      run: npm audit fix --force
+
+    - name: Debug Hexo Util
+      run: ls -R node_modules/hexo-util || echo "Hexo-util not found"
+
     - name: Deploy
       id: deploy
-      uses: sma11black/hexo-action@v1.0.3
+      uses: QyInvoLing/hexo-action@1.0.6
       with:
         deploy_key: ${{ secrets.DEPLOY_KEY }}
-        user_name: pruderior  # (or delete this input setting to use bot account)
-        user_email: pruderior@gmail.com # (or delete this input setting to use bot account)
-        commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)
-        
-    # Use the output from the `deploy` step(use for test action)
+        user_name: pruderior  
+        user_email: pruderior@gmail.com  
+        commit_msg: ${{ github.event.head_commit.message }}  
+
     - name: Get the output
       run: |
         echo "${{ steps.deploy.outputs.notify }}"
